env:
  global:
    - CC_TEST_REPORTER_ID=bb5acc458692373f5b6fcc54ca628817b725503d3dcd16934d68ffc84b80f085
sudo: false
language: node_js
node_js:
  - "7.0"

cache:
  directories:
    - node_modules

install:
  - npm install


script:
  - npm run lint
  - npm run test
  - npm run test:dev
  - gulp deploy
